/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活探針（liveness）
         * @description 確認 API 行程是否存活，永遠輕量回 200，不檢查任何外部依賴。
         *     供 k8s livenessProbe / 負載平衡器存活檢查使用。無需認證。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 行程存活 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": true,
                         *       "data": {
                         *         "status": "ok",
                         *         "timestamp": "2024-01-01T00:00:00.000Z"
                         *       },
                         *       "timestamp": "2024-01-01T00:00:00.000Z"
                         *     }
                         */
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            data: {
                                /**
                                 * @description 固定為 ok
                                 * @example ok
                                 */
                                status: string;
                                /**
                                 * Format: date-time
                                 * @description 探針回應時間
                                 */
                                timestamp: string;
                            };
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 就緒探針（readiness）
         * @description 檢查 API 是否可服務流量：主動探測資料庫（SELECT 1）與 Redis（PING）。
         *     任一依賴異常時回 503，供 k8s readinessProbe 暫停導流。無需認證。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 所有依賴正常 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": true,
                         *       "data": {
                         *         "status": "ok",
                         *         "info": {
                         *           "database": {
                         *             "status": "up"
                         *           },
                         *           "redis": {
                         *             "status": "up"
                         *           }
                         *         },
                         *         "error": {},
                         *         "details": {
                         *           "database": {
                         *             "status": "up"
                         *           },
                         *           "redis": {
                         *             "status": "up"
                         *           }
                         *         }
                         *       },
                         *       "timestamp": "2024-01-01T00:00:00.000Z"
                         *     }
                         */
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @description terminus 健康檢查結果 */
                            data: {
                                /**
                                 * @description 整體狀態（全部正常為 ok）
                                 * @example ok
                                 */
                                status: string;
                                /** @description 正常依賴的明細 */
                                info: Record<string, never>;
                                /** @description 異常依賴的明細（全部正常時為空物件） */
                                error: Record<string, never>;
                                /** @description 所有依賴的彙整明細 */
                                details: Record<string, never>;
                            };
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /**
                 * @description 一個以上依賴異常（DB 無法查詢或 Redis 無回應）。
                 *     逐項細節經由全域例外過濾器收斂為標準錯誤格式，code 為 SERVICE_UNAVAILABLE。
                 */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": false,
                         *       "message": "Service Unavailable",
                         *       "code": "SERVICE_UNAVAILABLE",
                         *       "timestamp": "2024-01-01T00:00:00.000Z"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登入
         * @description 使用 Email 與密碼登入，成功後取得 JWT Access Token 與 Refresh Token。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: email
                         * @description 電子郵件
                         * @example test@example.com
                         */
                        email: string;
                        /**
                         * Format: password
                         * @description 密碼
                         * @example mypassword123
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登入成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": true,
                         *       "data": {
                         *         "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                         *         "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                         *         "accessTokenExpiresIn": 900,
                         *         "refreshTokenExpiresIn": 604800,
                         *         "member": {
                         *           "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
                         *           "email": "test@example.com",
                         *           "member": "Alan",
                         *           "roleName": "ADMIN"
                         *         }
                         *       },
                         *       "timestamp": "2024-01-01T00:00:00.000Z"
                         *     }
                         */
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @description 登入結果 */
                            data: {
                                /** @description Access Token */
                                accessToken: string;
                                /** @description Refresh Token */
                                refreshToken: string;
                                /** @description Access Token 絕對有效期（秒） */
                                accessTokenExpiresIn: number;
                                /** @description Refresh Token 絕對有效期（秒） */
                                refreshTokenExpiresIn: number;
                                /** @description 帳號摘要 */
                                member: {
                                    /**
                                     * Format: uuid
                                     * @description 帳號 ID
                                     */
                                    id: string;
                                    /**
                                     * Format: email
                                     * @description Email
                                     */
                                    email: string;
                                    /** @description 名稱 */
                                    member: string;
                                    /** @description 所屬角色名稱 */
                                    roleName: string;
                                };
                            };
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description 帳號或密碼錯誤 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": false,
                         *       "message": "帳號或密碼錯誤",
                         *       "code": "UNAUTHORIZED",
                         *       "timestamp": "2024-01-01T00:00:00.000Z"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 登出
         * @description 登出並將 Access Token 加入黑名單。
         *     若同時傳入 Refresh Token，也會一併加入黑名單。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description Refresh Token（選填，一併廢棄）
                         * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                         */
                        refreshToken?: string;
                    };
                };
            };
            responses: {
                /** @description 登出成功（無回應內容） */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                401: components["responses"]["NoToken"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 更新 Access Token
         * @description 使用 Refresh Token 取得新的 Access Token 與新的 Refresh Token（rotation）。
         *     舊 Refresh Token 會立即加入黑名單；如果同一個舊 Refresh Token 再次被用 → 401。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description Refresh Token
                         * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                         */
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": true,
                         *       "data": {
                         *         "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                         *         "accessTokenExpiresIn": 7200,
                         *         "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
                         *         "refreshTokenExpiresIn": 604800
                         *       },
                         *       "timestamp": "2024-01-01T00:00:00.000Z"
                         *     }
                         */
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @description 更新後的 token 雙包 */
                            data: {
                                /** @description 新的 Access Token */
                                accessToken: string;
                                /** @description Access Token 絕對有效期（秒） */
                                accessTokenExpiresIn: number;
                                /** @description 新的 Refresh Token（舊 token 已加入黑名單） */
                                refreshToken: string;
                                /** @description Refresh Token 絕對有效期（秒） */
                                refreshTokenExpiresIn: number;
                            };
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                /** @description Refresh Token 無效或已失效 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": false,
                         *       "message": "Refresh Token 無效",
                         *       "code": "INVALID_REFRESH_TOKEN",
                         *       "timestamp": "2024-01-01T00:00:00.000Z"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                403: components["responses"]["Forbidden"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢個人帳號資料
         * @description 取得目前登入帳號的個人資料。
         *     無需任何額外 permission，持有有效 JWT 即可呼叫。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": true,
                         *       "data": {
                         *         "id": "11111111-1111-4111-8111-111111111111",
                         *         "email": "user@example.com",
                         *         "member": "王小明",
                         *         "roleId": "22222222-2222-4222-8222-222222222222",
                         *         "roleName": "管理者",
                         *         "roleCode": "SUPERADMIN",
                         *         "status": true,
                         *         "isDefault": false,
                         *         "lastLoginAt": "2026-04-30T10:00:00.000Z",
                         *         "createdAt": "2026-01-01T00:00:00.000Z",
                         *         "updatedAt": "2026-04-30T10:00:00.000Z",
                         *         "permissionCodes": [
                         *           "BACKEND:ACCOUNT:VIEW",
                         *           "BACKEND:ACCOUNT:EDIT"
                         *         ]
                         *       },
                         *       "timestamp": "2026-04-30T10:00:00.000Z"
                         *     }
                         */
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /** @description 帳號詳細 */
                            data: {
                                /**
                                 * Format: uuid
                                 * @description 帳號 ID
                                 */
                                id?: string;
                                /**
                                 * Format: email
                                 * @description Email
                                 */
                                email?: string;
                                /** @description 名稱 */
                                member?: string;
                                /**
                                 * Format: uuid
                                 * @description 所屬角色 ID
                                 */
                                roleId?: string;
                                /** @description 角色名稱 */
                                roleName?: string;
                                /**
                                 * @description 角色代碼（如 SUPERADMIN），給前端 sidebar 粗粒度 role gate 用；context 取不到時為 null
                                 * @example SUPERADMIN
                                 */
                                roleCode?: string | null;
                                /** @description 啟用狀態 */
                                status?: boolean;
                                /** @description 預設帳號旗標 */
                                isDefault?: boolean;
                                /**
                                 * Format: date-time
                                 * @description 最後登入時間（UTC，可 null）
                                 */
                                lastLoginAt?: string | null;
                                /**
                                 * Format: date-time
                                 * @description 建立時間（UTC）
                                 */
                                createdAt?: string;
                                /**
                                 * Format: date-time
                                 * @description 更新時間（UTC）
                                 */
                                updatedAt?: string;
                                /**
                                 * @description 該帳號目前持有的權限代碼（即時查 DB，非 JWT 快取）
                                 * @example [
                                 *       "BACKEND:ACCOUNT:VIEW",
                                 *       "BACKEND:ACCOUNT:EDIT"
                                 *     ]
                                 */
                                permissionCodes?: string[];
                            };
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                401: components["responses"]["NoToken"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 轉換文章列表（分頁）
         * @description 取得由 PPT 轉換而來的文章清單（精簡欄位），依建立時間倒序。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼 */
                    page?: number;
                    /** @description 每頁筆數 */
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            data: {
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @description 文章標題 */
                                    title: string;
                                    /** @description 來源 PPT 檔名 */
                                    sourceFilename: string;
                                    /** @description 投影片頁數 */
                                    slideCount: number;
                                    /** @description 整體準確率（0~1） */
                                    accuracyOverall: number;
                                    /**
                                     * @description 轉換狀態
                                     * @enum {string}
                                     */
                                    status: "success" | "partial" | "failed";
                                    /** Format: date-time */
                                    createdAt: string;
                                }[];
                                meta: {
                                    page: number;
                                    limit: number;
                                    total: number;
                                    totalPages: number;
                                };
                            };
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                401: components["responses"]["NoToken"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 手動觸發一次攝取
         * @description 立即掃描來源資料夾（模擬公槽）、轉換所有 .pptx、存檔並依策略處置來源檔，
         *     回傳本批次結果摘要。demo 方便用，正式由排程自動執行。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 攝取完成 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            data: {
                                /** Format: uuid */
                                id: string;
                                /** @enum {string} */
                                trigger: "scheduled" | "manual";
                                /** Format: date-time */
                                startedAt: string;
                                /** Format: date-time */
                                finishedAt: string | null;
                                filesScanned: number;
                                filesConverted: number;
                                filesFailed: number;
                                /** Format: date-time */
                                createdAt: string;
                                detail: {
                                    filename: string;
                                    /** @enum {string} */
                                    status: "success" | "failed";
                                    /** Format: uuid */
                                    articleId?: string | null;
                                    accuracyOverall?: number | null;
                                    error?: string | null;
                                }[];
                            };
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                401: components["responses"]["NoToken"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/articles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 取得單篇轉換文章
         * @description 取得單篇文章完整內容：不跑版 HTML、分類準確率（含每頁明細）、
         *     以及供「來源元素對照」面板使用的逐頁元素清單。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description 文章 ID */
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            data: {
                                /** Format: uuid */
                                id: string;
                                title: string;
                                sourceFilename: string;
                                /** @description 不跑版的完整 HTML（多頁堆疊，圖片以 data URI 內嵌） */
                                html: string;
                                slideCount: number;
                                /** @enum {string} */
                                status: "success" | "partial" | "failed";
                                /** Format: date-time */
                                createdAt: string;
                                accuracy: {
                                    /** @description 整體準確率（0~1） */
                                    overall: number;
                                    /** @description 文字還原正確率 */
                                    text: number;
                                    /** @description 圖片擷取成功率 */
                                    image: number;
                                    /** @description 元素涵蓋率 */
                                    coverage: number;
                                    /** @description 每頁準確率明細 */
                                    slides: {
                                        index: number;
                                        coverage: number;
                                        text: number;
                                        image: number;
                                        overall: number;
                                    }[];
                                };
                                /** @description 逐頁來源元素清單（對照面板用） */
                                inventory: {
                                    index: number;
                                    elements: {
                                        /** @enum {string} */
                                        kind: "text" | "image" | "table" | "unsupported";
                                        /** @description 是否成功還原到 HTML */
                                        restored: boolean;
                                        text?: string | null;
                                        /** @description 圖片 data URI（成功擷取時） */
                                        image?: string | null;
                                        tableCells?: string[][] | null;
                                        /** @description 未支援元素型別（chart / smartArt 等） */
                                        unsupportedType?: string | null;
                                    }[];
                                }[];
                            };
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                401: components["responses"]["NoToken"];
                /** @description 找不到文章 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "success": false,
                         *       "message": "找不到指定的文章",
                         *       "code": "ARTICLE_NOT_FOUND",
                         *       "timestamp": "2026-06-05T00:00:00.000Z"
                         *     }
                         */
                        "application/json": components["schemas"]["ErrorResponse"];
                    };
                };
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversion-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 轉換批次紀錄列表（分頁）
         * @description 取得各次攝取批次的觸發方式、起迄時間與成功/失敗檔數，依時間倒序。
         */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            data: {
                                items: {
                                    /** Format: uuid */
                                    id: string;
                                    /** @enum {string} */
                                    trigger: "scheduled" | "manual";
                                    /** Format: date-time */
                                    startedAt: string;
                                    /** Format: date-time */
                                    finishedAt: string | null;
                                    filesScanned: number;
                                    filesConverted: number;
                                    filesFailed: number;
                                    /** Format: date-time */
                                    createdAt: string;
                                    detail: {
                                        filename: string;
                                        /** @enum {string} */
                                        status: "success" | "failed";
                                        /** Format: uuid */
                                        articleId?: string | null;
                                        accuracyOverall?: number | null;
                                        error?: string | null;
                                    }[];
                                }[];
                                meta: {
                                    page: number;
                                    limit: number;
                                    total: number;
                                    totalPages: number;
                                };
                            };
                            /** Format: date-time */
                            timestamp: string;
                        };
                    };
                };
                401: components["responses"]["NoToken"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description 通用成功回應格式 */
        SuccessResponse: {
            /**
             * @description 操作是否成功
             * @example true
             */
            success: boolean;
            /** @description 回應資料 */
            data?: Record<string, never> | null;
            /**
             * Format: date-time
             * @description 回應時間
             * @example 2024-01-01T00:00:00.000Z
             */
            timestamp: string;
        };
        /** @description 通用錯誤回應格式 */
        ErrorResponse: {
            /**
             * @description 操作是否成功
             * @example false
             */
            success: boolean;
            /**
             * @description 錯誤訊息
             * @example 發生錯誤
             */
            message?: string;
            /**
             * @description 錯誤代碼
             * @example ERROR_CODE
             */
            code?: string;
            /**
             * Format: date-time
             * @description 回應時間
             * @example 2024-01-01T00:00:00.000Z
             */
            timestamp: string;
        };
    };
    responses: {
        /** @description 請求參數錯誤 */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "message": "請求參數錯誤",
                 *       "code": "BAD_REQUEST",
                 *       "timestamp": "2024-01-01T00:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 缺少授權憑證 */
        NoToken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "message": "缺少授權憑證，請先登入",
                 *       "code": "NO_TOKEN",
                 *       "timestamp": "2024-01-01T00:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Token 已登出或失效 */
        TokenRevoked: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "message": "Token 已登出或失效",
                 *       "code": "TOKEN_REVOKED",
                 *       "timestamp": "2024-01-01T00:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Token 已過期 */
        TokenExpired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "message": "Token 已過期",
                 *       "code": "TOKEN_EXPIRED",
                 *       "timestamp": "2024-01-01T00:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Token 無效 */
        InvalidToken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "message": "Token 無效",
                 *       "code": "INVALID_TOKEN",
                 *       "timestamp": "2024-01-01T00:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 權限不足 */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "message": "權限不足",
                 *       "code": "FORBIDDEN",
                 *       "timestamp": "2024-01-01T00:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 資源不存在 */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "message": "資源不存在",
                 *       "code": "NOT_FOUND",
                 *       "timestamp": "2024-01-01T00:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 資源已存在 */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "message": "資源已存在",
                 *       "code": "CONFLICT",
                 *       "timestamp": "2024-01-01T00:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 伺服器內部錯誤 */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "success": false,
                 *       "message": "伺服器發生未預期錯誤",
                 *       "code": "INTERNAL_SERVER_ERROR",
                 *       "timestamp": "2024-01-01T00:00:00.000Z"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
